name: app_medicamentos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.0
  path_provider: ^2.1.5
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.2
  provider: ^6.1.2
  wakelock_plus: ^1.2.10
#  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true